# Generated by Django 4.0.6 on 2022-09-07 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_profile_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 11, 7, 56, 468643)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
